-- --Tramites

CREATE TABLE TRAM_TRAMITE (ID_TRAM VARCHAR(36) NOT NULL, NOMBRE_TRAM VARCHAR(255), DESCRIPCION_TRAM TEXT, NORMATIVA_TRAM TEXT);

ALTER TABLE TRAM_TRAMITE ADD CONSTRAINT PK_TRAM PRIMARY KEY (ID_TRAM);

-- --Circuitos

CREATE TABLE CIRC_CIRCUITO (ID_CIRC VARCHAR(36) NOT NULL, ID_TRAM VARCHAR(36), NOMBRE_CIRC VARCHAR(255), DESCRIPCION_CIRC TEXT,
									 NORMATIVA_CIRC TEXT, ACTIVO ENUM('S','N'), FECHA_ALTA DATETIME, FECHA_MODIFICACION DATETIME, FECHA_BAJA DATETIME);
									 
ALTER TABLE CIRC_CIRCUITO ADD CONSTRAINT PK_CIRC PRIMARY KEY (ID_CIRC); 									 
									 
ALTER TABLE CIRC_CIRCUITO ADD CONSTRAINT FK_CIRC_TRAM FOREIGN KEY (ID_TRAM) REFERENCES TRAM_TRAMITE (ID_TRAM);

-- --Relacion de los circuitos con los tipos de elemento

CREATE TABLE TICI_TIEL_CIRC (COD_TIEL VARCHAR(10) NOT NULL, ID_CIRC VARCHAR(36) NOT NULL);

ALTER TABLE TICI_TIEL_CIRC ADD CONSTRAINT PK_TICI PRIMARY key (COD_TIEL, ID_CIRC);

ALTER TABLE TICI_TIEL_CIRC ADD CONSTRAINT FK_TICI_CIRC FOREIGN KEY (ID_CIRC) REFERENCES CIRC_CIRCUITO (ID_CIRC);

ALTER TABLE TICI_TIEL_CIRC ADD CONSTRAINT FK_TICI_TIEL FOREIGN KEY (COD_TIEL) references  tiel_tipo_elemento (COD_TIEL);

-- --Grupos de usuario que pueden modificar el circuito

CREATE TABLE CIGU_CIRC_GUAP (ID_CIRC VARCHAR(36) NOT NULL, ID_GUAP VARCHAR(36) NOT NULL);

ALTER TABLE CIGU_CIRC_GUAP ADD CONSTRAINT PK_CIGU PRIMARY KEY (ID_CIRC, ID_GUAP);

ALTER TABLE CIGU_CIRC_GUAP ADD CONSTRAINT FK_CIGU_CIRC FOREIGN KEY (ID_CIRC) REFERENCES CIRC_CIRCUITO (ID_CIRC);

ALTER TABLE CIGU_CIRC_GUAP ADD CONSTRAINT FK_CIGU_GUAP FOREIGN KEY (ID_GUAP) REFERENCES guap_grupo_usuario_aplicacion (ID_GUAP);


-- --Codigos de acciones de usuario

CREATE TABLE ACUS_ACCION_USUARIO (COD_ACUS VARCHAR(20) NOT NULL, NOMBRE_ACUS VARCHAR(255));

ALTER TABLE ACUS_ACCION_USUARIO ADD CONSTRAINT PK_ACUS PRIMARY KEY (COD_ACUS);

-- --Tabla de acciones

CREATE TABLE ACCI_ACCION (ID_ACCI VARCHAR(36) NOT NULL, NOMBRE_ACCI VARCHAR(36));

ALTER TABLE ACCI_ACCION ADD CONSTRAINT PK_ACCI PRIMARY KEY (ID_ACCI);


-- --Propiedades de las acciones que se van a realizar en cada paso

CREATE TABLE ACTI_ACCI_TIEL (ID_ACCI VARCHAR(36) NOT NULL, COD_TIEL VARCHAR(36), LLAMAR_SW ENUM('S','N'), PUNTO_ACCESO_SW TEXT, LLAMAR_LIB_NET ENUM('S','N'),
									  LIBRERIA_NET TEXT, METODO_NET TEXT, ACCION_USUARIO ENUM('S','N'), COD_ACUS VARCHAR(20));
									  
ALTER TABLE ACTI_ACCI_TIEL ADD CONSTRAINT PK_ACTI PRIMARY KEY (ID_ACCI);

ALTER TABLE ACTI_ACCI_TIEL ADD CONSTRAINT FK_ACTI_ACCI FOREIGN KEY (ID_ACCI) REFERENCES ACCI_ACCION (ID_ACCI);

ALTER TABLE ACTI_ACCI_TIEL ADD CONSTRAINT FK_ACTI_TIEL FOREIGN KEY (COD_TIEL) REFERENCES tiel_tipo_elemento (COD_TIEL);

ALTER TABLE ACTI_ACCI_TIEL ADD CONSTRAINT FK_ACTI_ACUS FOREIGN KEY (COD_ACUS) REFERENCES ACUS_ACCION_USUARIO (COD_ACUS);


-- --Tabla de estados

CREATE TABLE ESTA_ESTADO (COD_ESTA VARCHAR(20) NOT NULL, NOMBRE_ESTA VARCHAR(255), DESCRIPCION_ESTA TEXT);

ALTER TABLE ESTA_ESTADO ADD CONSTRAINT PK_ESTA PRIMARY KEY (COD_ESTA);

-- --Tabla de pasos

CREATE TABLE PASO_PASOS (ID_PASO VARCHAR(36) NOT NULL, ID_CIRC VARCHAR(36) NOT NULL, COD_ESTA VARCHAR(36) NOT NULL, COD_CIRC_SIG VARCHAR(36), COD_ESTA_SIG VARCHAR(36));

ALTER TABLE PASO_PASOS ADD CONSTRAINT PK_PASO PRIMARY KEY (ID_PASO);

ALTER TABLE PASO_PASOS ADD CONSTRAINT FK_PASO_CIRC_INICIAL FOREIGN KEY (ID_CIRC) REFERENCES CIRC_CIRCUITO (ID_CIRC);

ALTER TABLE PASO_PASOS ADD CONSTRAINT FK_PASO_ESTA_INICIAL FOREIGN KEY (COD_ESTA) REFERENCES ESTA_ESTADO (COD_ESTA);

ALTER TABLE PASO_PASOS ADD CONSTRAINT FK_PASO_CIRC_FINAL FOREIGN KEY (COD_CIRC_SIG) REFERENCES CIRC_CIRCUITO (ID_CIRC);

ALTER TABLE PASO_PASOS ADD CONSTRAINT FK_PASO_ESTA_FINAL FOREIGN KEY (COD_ESTA_SIG) REFERENCES ESTA_ESTADO (COD_ESTA);


-- --Permisos de paso por grupo

CREATE TABLE PSGU_PASO_GUAP (ID_PASO VARCHAR(36), ID_GUAP VARCHAR(36));

ALTER TABLE PSGU_PASO_GUAP ADD CONSTRAINT PK_PSGU PRIMARY KEY (ID_PASO, ID_GUAP);

ALTER TABLE PSGU_PASO_GUAP ADD CONSTRAINT FK_PSGU_PASO FOREIGN KEY (ID_PASO) REFERENCES PASO_PASOS (ID_PASO);


-- --Permisos de paso por usuario

CREATE TABLE PSUS_PASO_USUA (ID_PASO VARCHAR(36), ID_USUA VARCHAR(36));

ALTER TABLE PSUS_PASO_USUA ADD CONSTRAINT PK_PSUS PRIMARY KEY (ID_PASO, ID_USUA);

ALTER TABLE PSUS_PASO_USUA ADD CONSTRAINT FK_PSUS_PASO FOREIGN KEY (ID_PASO) REFERENCES PASO_PASOS (ID_PASO);		


-- --Acciones que se deben ejecutar en el paso

CREATE TABLE PSAC_PASO_ACCION (ID_PSAC BIGINT AUTO_INCREMENT PRIMARY key,
										 ID_PASO VARCHAR(36) NOT NULL,
										 TIPO_EJEC ENUM('PREPASO','POSTPASO') NOT NULL DEFAULT 'PREPASO',
										 ORDEN_EJECUCION INT,
										 ID_ACCI VARCHAR(36),
										 ID_CIRC_ERROR VARCHAR(36));	
										 


ALTER TABLE PSAC_PASO_ACCION ADD CONSTRAINT FK_PSAC_PASO FOREIGN KEY (ID_PASO) REFERENCES PASO_PASOS (ID_PASO);

ALTER TABLE PSAC_PASO_ACCION ADD CONSTRAINT FK_PSAC_ACCI FOREIGN KEY (ID_ACCI) REFERENCES ACCI_ACCION (ID_ACCI);

ALTER TABLE PSAC_PASO_ACCION ADD CONSTRAINT FK_PSAC_CIRC_ERR FOREIGN KEY (ID_CIRC_ERROR) REFERENCES CIRC_CIRCUITO (ID_CIRC);									 						  



-- --Estados de los elementos en base al circuito

CREATE TABLE ESEL_ESTADO_ELEMENTO (ID_ESEL BIGINT AUTO_INCREMENT PRIMARY key, ID_ELEM VARCHAR(36), FECHA_ESEL DATETIME, ID_USUA_TRAMITADOR VARCHAR(36), COD_ESTA VARCHAR(20), ID_CIRC VARCHAR(36));


ALTER TABLE ESEL_ESTADO_ELEMENTO ADD CONSTRAINT FK_ESEL_ELEM FOREIGN KEY (ID_ELEM) REFERENCES elem_elemento  (ID_ELEM);

ALTER TABLE ESEL_ESTADO_ELEMENTO ADD CONSTRAINT FK_ESEL_ESTA FOREIGN KEY (COD_ESTA) REFERENCES ESTA_ESTADO (COD_ESTA);

ALTER TABLE ESEL_ESTADO_ELEMENTO ADD CONSTRAINT FK_ESEL_CIRC FOREIGN KEY (ID_CIRC) REFERENCES CIRC_CIRCUITO (ID_CIRC);

ALTER TABLE ESEL_ESTADO_ELEMENTO ADD CONSTRAINT FK_ESEL_USUA FOREIGN KEY (ID_USUA_TRAMITADOR) REFERENCES usua_usuarios (ID_USUA);

-- --Estados siguientes esel

CREATE TABLE ESES_ESTADOS_ELEMENTO_SIGUIENTE (ID_ESEL BIGINT, ID_ESEL_SIGUIENTE BIGINT, ID_USUA_ENVIO VARCHAR(36), FECHA_ENVIO DATETIME);

ALTER TABLE ESES_ESTADOS_ELEMENTO_SIGUIENTE ADD CONSTRAINT PK_ESES PRIMARY KEY (ID_ESEL, ID_ESEL_SIGUIENTE);

ALTER TABLE ESES_ESTADOS_ELEMENTO_SIGUIENTE ADD CONSTRAINT FK_ESES_ESEL_INICIAL FOREIGN KEY (ID_ESEL) REFERENCES ESEL_ESTADO_ELEMENTO (ID_ESEL);
ALTER TABLE ESES_ESTADOS_ELEMENTO_SIGUIENTE ADD CONSTRAINT FK_ESES_ESEL_SIGUIENTE FOREIGN KEY (ID_ESEL_SIGUIENTE) REFERENCES ESEL_ESTADO_ELEMENTO (ID_ESEL);
ALTER TABLE ESES_ESTADOS_ELEMENTO_SIGUIENTE ADD CONSTRAINT FK_ESES_USUA FOREIGN KEY (ID_USUA_ENVIO) REFERENCES usua_usuarios (ID_USUA);
 									 