CREATE TABLE tpta_tipo_tarea (ID_TPTA VARCHAR(36) PRIMARY KEY, COD_TPTA VARCHAR(20) NOT NULL, NOMBRE_TPTA VARCHAR(60));
ALTER TABLE tpta_tipo_tarea ADD CONSTRAINT FK_TPTA_ELEM FOREIGN KEY (ID_TPTA) REFERENCES elem_elemento (ID_ELEM);

INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('tpta','Tipo de tarea');


CREATE TABLE tare_tarea (ID_TARE VARCHAR(36) PRIMARY key, ID_USUA_PROP VARCHAR(36), ID_TPTA VARCHAR(36), NOMBRE_TARE VARCHAR(60), DESCRIPCION_TARE TEXT);
ALTER TABLE tare_tarea ADD CONSTRAINT FK_TARE_ELEM FOREIGN KEY (ID_TARE) REFERENCES elem_elemento (ID_ELEM);
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('tare','Tarea programada');
ALTER TABLE tare_tarea ADD CONSTRAINT FK_TARE_USUA FOREIGN KEY (ID_USUA_PROP) REFERENCES usua_usuarios (ID_USUA);
ALTER TABLE tare_tarea ADD CONSTRAINT FK_TARE_TPTA FOREIGN KEY (ID_TPTA) REFERENCES tpta_tipo_tarea (ID_TPTA);

CREATE TABLE pgta_programacion_tarea (ID_PGTA VARCHAR(36) PRIMARY KEY, ID_TARE VARCHAR(36), DIAS_EJECUCION VARCHAR(7) DEFAULT '0000000', HORA_EJECUCION VARCHAR(5) DEFAULT '00:00', EJECUTAR_DIA DATETIME DEFAULT NULL, CREAR_ENTRADA_CALE ENUM('S','N') DEFAULT 'N', ID_ENCL VARCHAR(36) DEFAULT NULL);
ALTER TABLE pgta_programacion_tarea ADD CONSTRAINT FK_PGTA_ELEM FOREIGN KEY (ID_PGTA) REFERENCES elem_elemento (ID_ELEM);
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('pgta','Programación de tarea programada');
ALTER TABLE pgta_programacion_tarea ADD CONSTRAINT FK_PGTA_TARE FOREIGN KEY (ID_TARE) REFERENCES tare_tarea (ID_TARE);
ALTER TABLE pgta_programacion_tarea ADD CONSTRAINT FK_PGTA_ENCL FOREIGN KEY (ID_ENCL) REFERENCES encl_entrada_calendario (ID_ENCL);


CREATE TABLE tptb_tipo_trabajo (ID_TPTB VARCHAR(36) PRIMARY KEY, COD_TPTB VARCHAR(20), NOMBRE_TPTB VARCHAR(60), DESCRIPCION_TPTB TEXT);
ALTER TABLE tptb_tipo_trabajo ADD CONSTRAINT FK_TPTB_ELEM FOREIGN KEY (ID_TPTB) REFERENCES elem_elemento (ID_ELEM);
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('tptb','Tipo de trabajo');

CREATE TABLE trab_trabajo (ID_TRAB VARCHAR(36) PRIMARY KEY, ID_LETR_PADRE VARCHAR(36) DEFAULT NULL, ID_TRAB_PADRE VARCHAR(36) DEFAULT NULL, ID_USUA_PROG VARCHAR(36), FECHA_PROG DATETIME, ID_TPTB VARCHAR(36), ID_TARE VARCHAR(36) DEFAULT NULL);
ALTER TABLE trab_trabajo ADD CONSTRAINT FK_TRAB_ELEM FOREIGN KEY (ID_TRAB) REFERENCES elem_elemento (ID_ELEM);
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('trab','Trabajo programado');
ALTER TABLE trab_trabajo ADD CONSTRAINT FK_TRAB_TRAB FOREIGN KEY (ID_TRAB_PADRE) REFERENCES trab_trabajo (ID_TRAB);
ALTER TABLE trab_trabajo ADD CONSTRAINT FK_TRAB_USUA FOREIGN KEY (ID_USUA_PROG) REFERENCES usua_usuarios (ID_USUA);
ALTER TABLE trab_trabajo ADD CONSTRAINT FK_TRAB_TPTB FOREIGN KEY (ID_TPTB) REFERENCES tptb_tipo_trabajo (ID_TPTB);
ALTER TABLE trab_trabajo ADD CONSTRAINT FK_TRAB_TARE FOREIGN KEY (ID_TARE) REFERENCES tare_tarea (ID_TARE);

CREATE TABLE pmtr_parametros_trabajo (ID_PMTR INT, ID_TRAB VARCHAR(36), ID_LETR VARCHAR(36), NOMBRE_PMTR VARCHAR(60), VALOR_PMTR TEXT);
ALTER TABLE pmtr_parametros_trabajo ADD CONSTRAINT PRIMARY KEY (ID_PMTR, ID_TRAB, ID_LETR);


CREATE TABLE estr_estado_trabajo (COD_ESTR VARCHAR(10) PRIMARY key, NOMBRE_ESTR VARCHAR(60));

CREATE TABLE letr_linea_ejecucion_trabajo (ID_LETR VARCHAR(36) PRIMARY key, ID_TRAB VARCHAR(36), ID_HYDR VARCHAR(36), FECHA_LETR DATETIME, COD_ESTR VARCHAR(10), ESPERA_TRABAJOS ENUM('S','N') DEFAULT 'N', ESPERA_INTERACTIVO ENUM('S','N') DEFAULT 'N', OBSERVACIONES TEXT);
ALTER TABLE letr_linea_ejecucion_trabajo ADD CONSTRAINT FK_LETR_ELEM FOREIGN KEY (ID_LETR) REFERENCES elem_elemento (ID_ELEM);
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('letr','Linea de trabajo programado (Estado del trabajo)');

ALTER TABLE letr_linea_ejecucion_trabajo ADD CONSTRAINT FK_LETR_TRAB FOREIGN KEY (ID_TRAB) REFERENCES trab_trabajo (ID_TRAB);
ALTER TABLE letr_linea_ejecucion_trabajo ADD CONSTRAINT FK_LETR_HYDR FOREIGN KEY (ID_HYDR) REFERENCES hydr_hydras (ID_HYDR);
ALTER TABLE letr_linea_ejecucion_trabajo ADD CONSTRAINT FK_LETR_ESTR FOREIGN KEY (COD_ESTR) REFERENCES estr_estado_trabajo (COD_ESTR);


CREATE TABLE lgtr_log_trabajo (ID_LGTR BIGINT AUTO_INCREMENT PRIMARY KEY, ID_TRAB VARCHAR(36), ID_LETR VARCHAR(36) DEFAULT NULL, TIPO_LGTR ENUM('I','D','A','E') DEFAULT 'I', FECHA_LGTR DATETIME, MENSAJE_LGTR TEXT, DATOS_LGTR TEXT);
ALTER TABLE lgtr_log_trabajo ADD CONSTRAINT FK_LGTR_TRAB FOREIGN KEY (ID_TRAB) REFERENCES trab_trabajo (ID_TRAB);
ALTER TABLE lgtr_log_trabajo ADD CONSTRAINT FK_LGTR_LETR FOREIGN KEY (ID_LETR) REFERENCES letr_linea_ejecucion_trabajo (ID_LETR);

