CREATE TABLE hydr_hydras (ID_HYDR VARCHAR(36) PRIMARY key, NOMBRE_HYDR VARCHAR(60), ID_USUA_PROP VARCHAR(36), ID_USUA_EJEC VARCHAR(36));
ALTER TABLE hydr_hydras ADD CONSTRAINT FK_HYDR_ELEM FOREIGN KEY (ID_HYDR) REFERENCES elem_elemento (ID_ELEM);

INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('hydr','Cliente hydra lfvb');

ALTER TABLE hydr_hydras ADD CONSTRAINT FK_HYDR_USPR FOREIGN KEY (ID_USUA_PROP) REFERENCES usua_usuarios (ID_USUA);
ALTER TABLE hydr_hydras ADD CONSTRAINT FK_HYDR_USEJ FOREIGN KEY (ID_USUA_EJEC) REFERENCES usua_usuarios (ID_USUA);


CREATE TABLE lghd_log_hydra (ID_LGHD BIGINT AUTO_INCREMENT PRIMARY KEY, ID_HYDR VARCHAR(36), FECHA_LGHD DATETIME, IMPORTANCIA_LGHD ENUM('D','I','W','E') DEFAULT 'I', MENSAJE_LGHD TEXT, DATOS_LGHD TEXT);
ALTER TABLE lghd_log_hydra ADD CONSTRAINT FK_LGHD_HYDR FOREIGN KEY (ID_HYDR) REFERENCES hydr_hydras (ID_HYDR);
