CREATE TABLE tipe_tipo_persona (COD_TIPE VARCHAR(3), NOMBRE_TIPE VARCHAR(60));
ALTER TABLE tipe_tipo_persona ADD CONSTRAINT PRIMARY KEY (COD_TIPE);
INSERT INTO tipe_tipo_persona (COD_TIPE, NOMBRE_TIPE) VALUES ('F','Persona física');
INSERT INTO tipe_tipo_persona (COD_TIPE, NOMBRE_TIPE) VALUES ('J','Persona júridica');

CREATE TABLE pers_persona (ID_PERS VARCHAR(36), COD_TIPE VARCHAR(3), NOMBRE_PERS VARCHAR(255), APELLIDO1_PERS VARCHAR(255), APELLIDO2_PERS VARCHAR(255));
ALTER TABLE pers_persona ADD CONSTRAINT PRIMARY KEY (ID_PERS);
ALTER TABLE pers_persona ADD CONSTRAINT FK_PERS_TIPE FOREIGN KEY (COD_TIPE) REFERENCES tipe_tipo_persona (COD_TIPE);
ALTER TABLE pers_persona ADD CONSTRAINT FK_PERS_ELEM FOREIGN KEY (ID_PERS) REFERENCES elem_elemento (ID_ELEM);


CREATE TABLE elpe_elemento_persona (ID_PERS VARCHAR(36), ID_ELEM VARCHAR(36));
ALTER TABLE elpe_elemento_persona ADD CONSTRAINT PRIMARY KEY (ID_PERS, ID_ELEM);
ALTER TABLE elpe_elemento_persona ADD CONSTRAINT FK_ELPE_PERS FOREIGN KEY (ID_PERS) REFERENCES pers_persona (ID_PERS);
ALTER TABLE elpe_elemento_persona ADD CONSTRAINT FK_ELPE_ELEM FOREIGN KEY (ID_ELEM) REFERENCES elem_elemento (ID_ELEM);

CREATE TABLE tiid_tipo_identificador_persona (ID_TIID VARCHAR(36), COD_TIID VARCHAR(36), NOMBRE_TIID VARCHAR(60));
ALTER TABLE tiid_tipo_identificador_persona ADD CONSTRAINT PRIMARY KEY (COD_TIID);


CREATE TABLE idpe_identificador_persona (ID_IDPE VARCHAR(36), ID_PERS VARCHAR(36), COD_TIID VARCHAR(36), DATO1_IDPE VARCHAR(50), DATO2_IDPE VARCHAR(50), FECHA_INICIO_VIGENCIA DATETIME, FECHA_FIN_VIGENCIA DATETIME);
ALTER TABLE idpe_identificador_persona ADD CONSTRAINT PRIMARY KEY (ID_IDPE);
ALTER TABLE idpe_identificador_persona ADD CONSTRAINT FK_IDPE_PERS FOREIGN KEY (ID_PERS) REFERENCES pers_persona (ID_PERS);
ALTER TABLE idpe_identificador_persona ADD CONSTRAINT FK_IDPE_TIID FOREIGN KEY (COD_TIID) REFERENCES tiid_tipo_identificador_persona (COD_TIID);

CREATE TABLE trpr_tipo_relacion_persona (ID_TRPR VARCHAR(36), COD_TRPR VARCHAR(36), NOMBRE_REPE VARCHAR(255));
ALTER TABLE trpr_tipo_relacion_persona ADD CONSTRAINT PRIMARY KEY (COD_TRPR);

CREATE TABLE repe_relacion_persona (ID_PERS VARCHAR(36), COD_TRPR VARCHAR(36), ID_PERS_RELA VARCHAR(36), FECHA_INICIO_REPE DATETIME, FECHA_FIN_REPE DATETIME, OBSERVACIONES TEXT);
ALTER TABLE repe_relacion_persona ADD CONSTRAINT PRIMARY KEY (ID_PERS, COD_TRPR, ID_PERS_RELA);
ALTER TABLE repe_relacion_persona ADD CONSTRAINT FK_REPE_PERS FOREIGN KEY (ID_PERS) REFERENCES pers_persona (ID_PERS);
ALTER TABLE repe_relacion_persona ADD CONSTRAINT FK_REPE_PERS_RELA FOREIGN KEY (ID_PERS_RELA) REFERENCES pers_persona (ID_PERS);
ALTER TABLE repe_relacion_persona ADD CONSTRAINT FK_REPE_TRPR FOREIGN KEY (COD_TRPR) REFERENCES trpr_tipo_relacion_persona (COD_TRPR);


INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('pers','Persona');


CREATE TABLE sitp_tipo_situacion_persona (COD_SITP VARCHAR(10) PRIMARY KEY, NOMBRE_SITP VARCHAR(60));

CREATE TABLE sipe_situacion_persona (ID_SIPE VARCHAR(36) PRIMARY key, ID_PERS VARCHAR(36), COD_SITP VARCHAR(10), FECHA_INICIO DATETIME, FECHA_FIN DATETIME, OBSERVACIONES_SIPE TEXT);
ALTER TABLE sipe_situacion_persona ADD CONSTRAINT FK_SIPE_PERS FOREIGN KEY (ID_PERS) REFERENCES pers_persona (ID_PERS);
ALTER TABLE sipe_situacion_persona ADD CONSTRAINT FK_SIPE_SITP FOREIGN KEY (COD_SITP) REFERENCES sitp_tipo_situacion_persona (COD_SITP);

CREATE TABLE tsex_tipo_sexo_persona (COD_TSEX VARCHAR(10) PRIMARY key, NOMBRE_TSEX VARCHAR(60));

ALTER TABLE pers_persona ADD COLUMN (COD_TSEX VARCHAR(10));
ALTER TABLE pers_persona ADD CONSTRAINT FK_PERS_TSEX FOREIGN KEY (COD_TSEX) REFERENCES tsex_tipo_sexo_persona(COD_TSEX);

ALTER TABLE pers_persona ADD COLUMN (FECHA_NACIMIENTO DATETIME DEFAULT NULL);

INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('sipe','Situación persona');
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('trpr','Tipo relacion entre personas');
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('tiid','Tipo identificación de persona');
INSERT INTO tiel_tipo_elemento (COD_TIEL, NOMBRE_TIEL) VALUES ('idpe','Identificación de persona');
SIPE